name: first-workflow
on:
  push:
    branches:
      - "main"
  fork:
jobs:
  first-job:
   name: first-job
   runs-on: ubuntu-latest

   steps:
     - name: checkout step
       uses: actions/checkout@v4

     - name: list of files 
       run: |
              cd k8s
              ls 
       shell: bash



       